// ===========================================================================
// glb-poses.ts — extra bone-local poses for the rigged HumanArmature GLB (hero +
// NPCs), for the activities the baked clips don't cover: gym bench press, dance,
// swimming, the RC-operator stance, open-vehicle seating, weed-farm hand work, the
// taxi hail / cutscene talk gestures, and the roof-fall ragdoll.
//
// SAME pattern as AIM_POSE / CAR_POSE / MOTO_POSE in player-glb.ts: each pose is a
// map of bone name -> local Euler [x,y,z], applied AFTER mixer.update() to override
// (or, with `only`, overlay) the clip. The POSE CONSTANTS below are AUTO-GENERATED
// by tools/gen-glb-poses.ts (the same analytic IK as /studio, from geometric hand/
// foot targets) — re-run that tool to retune; don't hand-edit the numbers.
//
// The apply helpers are allocation-free (scratch + a cached bone map per root) so
// they're cheap to call every frame.
// ===========================================================================
import * as THREE from 'three';

export type Pose = Record<string, readonly [number, number, number]>;

// ---- AUTO-GENERATED by tools/gen-glb-poses.ts — do not hand-edit -----------
export const REMOTE_POSE: Pose = {
  Body: [-0.001, 0.005, 0.000],
  UpperLegL: [3.006, 0.048, -0.048], LowerLegL: [0.415, 0.000, -0.000], FootL: [-1.540, 0.011, -2.791],
  UpperLegR: [2.977, -0.038, 0.056], LowerLegR: [0.431, -0.000, 0.000], FootR: [-1.539, -0.005, 2.984],
  UpperArmL: [-1.205, 0.943, -2.051], LowerArmL: [0.025, -0.071, -1.437],
  UpperArmR: [-1.417, -0.983, 1.860], LowerArmR: [-0.025, -0.033, 1.390],
  Neck: [0.153, 0.000, 0.000], Head: [-0.231, -0.001, 0.006],
};
// Gym bench press — ARMS ONLY (the lying body's legs stay flat from the idle clip).
export const BENCH_LOCKOUT: Pose = {
  Body: [-0.001, 0.005, 0.000],
  UpperArmL: [-1.247, 0.730, -2.977], LowerArmL: [0.172, -0.187, -1.192],
  UpperArmR: [-1.306, -0.803, 2.937], LowerArmR: [0.161, 0.094, 1.146],
  Neck: [0.153, 0.000, 0.000], Head: [-0.231, -0.001, 0.006],
};
export const BENCH_CHEST: Pose = {
  Body: [-0.001, 0.005, 0.000],
  UpperArmL: [-1.344, 0.565, -1.622], LowerArmL: [-0.003, -0.347, -2.756],
  UpperArmR: [-1.509, -0.590, 1.239], LowerArmR: [-0.047, 0.156, 2.804],
  Neck: [0.153, 0.000, 0.000], Head: [-0.231, -0.001, 0.006],
};
export const DANCE_NEUTRAL: Pose = {
  Body: [-0.001, 0.005, 0.000],
  UpperLegL: [3.006, 0.048, -0.048], LowerLegL: [0.415, 0.000, -0.000], FootL: [-1.540, 0.011, -2.791],
  UpperLegR: [2.977, -0.038, 0.056], LowerLegR: [0.431, -0.000, 0.000], FootR: [-1.539, -0.005, 2.984],
  UpperArmL: [-1.345, 0.779, -1.285], LowerArmL: [0.178, -0.229, -1.377],
  UpperArmR: [-1.537, -0.729, 1.144], LowerArmR: [0.127, 0.100, 1.333],
  Neck: [0.153, 0.000, 0.000], Head: [-0.231, -0.001, 0.006],
};
export const DANCE_UP: Pose = {
  Body: [-0.001, 0.005, 0.000],
  UpperLegL: [3.006, 0.048, -0.048], LowerLegL: [0.415, 0.000, -0.000], FootL: [-1.540, 0.011, -2.791],
  UpperLegR: [2.977, -0.038, 0.056], LowerLegR: [0.431, -0.000, 0.000], FootR: [-1.539, -0.005, 2.984],
  UpperArmL: [-1.499, 0.735, 0.662], LowerArmL: [0.088, 0.060, 1.395],
  UpperArmR: [-1.313, -0.520, -0.546], LowerArmR: [0.246, -0.279, -1.247],
  Neck: [0.153, 0.000, 0.000], Head: [-0.231, -0.001, 0.006],
};
export const DANCE_DOWN: Pose = {
  Body: [-0.001, 0.005, 0.000],
  UpperLegL: [2.808, 0.061, -0.080], LowerLegL: [0.426, 0.000, 0.011], FootL: [-1.540, 0.011, -2.791],
  UpperLegR: [2.806, -0.050, 0.077], LowerLegR: [0.433, -0.000, -0.012], FootR: [-1.539, -0.005, 2.984],
  UpperArmL: [-1.351, 0.598, -1.892], LowerArmL: [0.186, -0.178, -1.066],
  UpperArmR: [-1.515, -0.624, 1.811], LowerArmR: [0.146, 0.060, 0.998],
  Neck: [0.153, 0.000, 0.000], Head: [-0.231, -0.001, 0.006],
};
export const DANCE_LEFT: Pose = {
  Body: [-0.001, 0.005, 0.000],
  UpperLegL: [3.006, 0.048, -0.048], LowerLegL: [0.415, 0.000, -0.000], FootL: [-1.540, 0.011, -2.791],
  UpperLegR: [2.977, -0.038, 0.056], LowerLegR: [0.431, -0.000, 0.000], FootR: [-1.539, -0.005, 2.984],
  UpperArmL: [-1.209, 0.260, -0.895], LowerArmL: [1.930, -0.794, -0.295],
  UpperArmR: [-1.481, -1.102, 1.573], LowerArmR: [-0.163, -0.186, 1.647],
  Neck: [0.153, 0.000, 0.000], Head: [-0.231, -0.001, 0.006],
};
export const DANCE_RIGHT: Pose = {
  Body: [-0.001, 0.005, 0.000],
  UpperLegL: [3.006, 0.048, -0.048], LowerLegL: [0.415, 0.000, -0.000], FootL: [-1.540, 0.011, -2.791],
  UpperLegR: [2.977, -0.038, 0.056], LowerLegR: [0.431, -0.000, 0.000], FootR: [-1.539, -0.005, 2.984],
  UpperArmL: [-1.185, 1.091, -1.877], LowerArmL: [-0.077, 0.062, -1.701],
  UpperArmR: [-1.367, -0.229, 0.826], LowerArmR: [1.849, 0.684, 0.414],
  Neck: [0.153, 0.000, 0.000], Head: [-0.231, -0.001, 0.006],
};
export const SWIM_PRONE: Pose = {
  Body: [-0.001, 0.005, 0.000],
  UpperLegL: [2.668, 0.086, -0.169], LowerLegL: [2.111, -0.008, -0.007], FootL: [-1.540, 0.011, -2.791],
  UpperLegR: [2.682, -0.070, 0.155], LowerLegR: [2.106, 0.002, 0.002], FootR: [-1.539, -0.005, 2.984],
  UpperArmL: [-1.241, 0.759, -2.684], LowerArmL: [0.103, -0.226, -1.807],
  UpperArmR: [-1.353, -0.829, 2.556], LowerArmR: [0.063, 0.116, 1.800],
  Neck: [0.153, 0.000, 0.000], Head: [-0.231, -0.001, 0.006],
};
export const SWIM_TREAD: Pose = {
  Body: [-0.001, 0.005, 0.000],
  UpperLegL: [1.287, 0.043, 0.053], LowerLegL: [1.841, -0.100, -0.115], FootL: [-1.540, 0.011, -2.791],
  UpperLegR: [1.290, -0.058, -0.038], LowerLegR: [1.847, 0.077, 0.090], FootR: [-1.539, -0.005, 2.984],
  UpperArmL: [-1.319, 0.349, -1.360], LowerArmL: [0.565, -0.674, -1.444],
  UpperArmR: [-1.478, -0.330, 1.264], LowerArmR: [0.515, 0.540, 1.485],
  Neck: [0.153, 0.000, 0.000], Head: [-0.231, -0.001, 0.006],
};
// weed-farm hand work — RIGHT arm only (overlaid on the locomotion clip via `only`). Carry
// needs no pose (the bucket just rides the walk cycle); pour tips the arm up, deal reaches out.
export const WEED_POUR: Pose = { UpperArmR: [-1.490, -0.711, 1.924], LowerArmR: [0.100, 0.098, 1.464] };
export const WEED_DEAL: Pose = { UpperArmR: [-1.412, -0.808, 2.285], LowerArmR: [0.088, 0.006, 0.839] };
// NPC gestures — overlaid (right arm + head for the wave; both arms for talking).
export const NPC_WAVE: Pose = { UpperArmR: [-0.920, -0.010, -0.046], LowerArmR: [1.536, -0.504, -0.536] };
export const NPC_TALK: Pose = {
  UpperArmL: [-1.355, 0.563, -1.797], LowerArmL: [0.202, -0.330, -1.650],
  UpperArmR: [-1.519, -0.584, 1.664], LowerArmR: [0.155, 0.200, 1.646],
};
export const RAGDOLL: Pose = {
  Body: [-0.001, 0.005, 0.000],
  UpperLegL: [1.693, 0.098, -0.016], LowerLegL: [1.754, -0.060, -0.076], FootL: [-1.540, 0.011, -2.791],
  UpperLegR: [1.699, -0.099, 0.026], LowerLegR: [1.758, 0.049, 0.062], FootR: [-1.539, -0.005, 2.984],
  UpperArmL: [-1.196, 0.421, -0.529], LowerArmL: [2.406, 0.208, 0.331],
  UpperArmR: [-1.371, -0.387, 0.513], LowerArmR: [2.285, -0.498, -0.297],
  Neck: [0.153, 0.000, 0.000], Head: [-0.231, -0.001, 0.006],
};
// ---- end generated ----------------------------------------------------------

// cached bone lookup per root (avoids re-traversing every frame)
const _maps = new WeakMap<THREE.Object3D, Map<string, THREE.Bone>>();
function boneMap(root: THREE.Object3D): Map<string, THREE.Bone> {
  let m = _maps.get(root);
  if (m) return m;
  m = new Map();
  root.traverse(o => { if ((o as THREE.Bone).isBone) m!.set(o.name, o as THREE.Bone); });
  _maps.set(root, m);
  return m;
}
const _fp = new THREE.Vector3();
// Re-attach each Foot (its own root-parented chain) onto its shin end, so the foot
// follows the posed leg instead of floating at the bind position. Same fix used by
// applyVehiclePose in player-glb.ts.
function reconnectFeet(bones: Map<string, THREE.Bone>): void {
  for (const s of ['L', 'R'] as const) {
    const end = bones.get('LowerLeg' + s + '_end'), foot = bones.get('Foot' + s);
    if (end && foot && foot.parent) { _fp.setFromMatrixPosition(end.matrixWorld); foot.parent.worldToLocal(_fp); foot.position.copy(_fp); foot.updateMatrixWorld(true); }
  }
}

// Apply a pose to the GLB. `only` overlays just those bones (rest keeps the clip);
// `feet` re-attaches the foot bones after a leg-bearing pose. Call AFTER mixer.update().
export function applyPose(root: THREE.Object3D, pose: Pose, opts?: { feet?: boolean; only?: readonly string[] }): void {
  const bones = boneMap(root);
  const names = opts?.only ?? Object.keys(pose);
  for (const name of names) {
    const r = pose[name]; if (!r) continue;
    const b = bones.get(name); if (b) b.rotation.set(r[0], r[1], r[2]);
  }
  root.updateMatrixWorld(true);
  if (opts?.feet) { reconnectFeet(bones); }
}

// Per-bone linear blend of two full poses (t: 0→a, 1→b), allocation-free. Used for the
// animated lifts/sways (bench, dance, swim) where two keyframes interpolate each frame.
const _ea: [number, number, number] = [0, 0, 0];
export function applyBlend(root: THREE.Object3D, a: Pose, b: Pose, t: number, feet = true): void {
  const bones = boneMap(root);
  for (const name in a) {
    const ra = a[name], rb = b[name] ?? ra;
    const bone = bones.get(name); if (!bone) continue;
    _ea[0] = ra[0] + (rb[0] - ra[0]) * t;
    _ea[1] = ra[1] + (rb[1] - ra[1]) * t;
    _ea[2] = ra[2] + (rb[2] - ra[2]) * t;
    bone.rotation.set(_ea[0], _ea[1], _ea[2]);
  }
  root.updateMatrixWorld(true);
  if (feet) reconnectFeet(bones);
}

// Add a small delta (radians) to one bone's rotation AFTER a pose was applied — the
// cheap "life" layer (swim flutter, wave swing, ragdoll jiggle). No allocation.
export function nudgeBone(root: THREE.Object3D, name: string, dx: number, dy: number, dz: number): void {
  const b = boneMap(root).get(name);
  if (b) { b.rotation.x += dx; b.rotation.y += dy; b.rotation.z += dz; }
}

// ---- ready-made animated drivers -------------------------------------------
// Gym bench press: p=1 lockout (arms extended), p=0 bar at chest.
export function applyBench(root: THREE.Object3D, p: number): void {
  applyBlend(root, BENCH_CHEST, BENCH_LOCKOUT, p < 0 ? 0 : p > 1 ? 1 : p, true);
}
const DANCE_LANES: Pose[] = [DANCE_LEFT, DANCE_DOWN, DANCE_UP, DANCE_RIGHT]; // matches dance-game lane ids 0..3
// Dance: blend the neutral groove toward the hit pose for `lane` by `amt` (0..1).
export function applyDance(root: THREE.Object3D, lane: number, amt: number): void {
  const target = DANCE_LANES[lane] ?? DANCE_NEUTRAL;
  applyBlend(root, DANCE_NEUTRAL, target, amt < 0 ? 0 : amt > 1 ? 1 : amt, true);
}
// Swimming: blend tread<->prone by `moving` (0 floating, 1 crawling forward), then add a
// gentle alternating flutter kick + arm scull so it reads as swimming, not a frozen pose.
// `t` is the stroke phase (radians) so the motion matches the swim cadence/splashes.
export function applySwim(root: THREE.Object3D, moving: number, t: number): void {
  applyBlend(root, SWIM_TREAD, SWIM_PRONE, moving < 0 ? 0 : moving > 1 ? 1 : moving, false);
  const kick = Math.sin(t * 2) * 0.3, scull = Math.sin(t) * 0.22;
  nudgeBone(root, 'LowerLegL', kick, 0, 0);
  nudgeBone(root, 'LowerLegR', -kick, 0, 0);
  nudgeBone(root, 'UpperArmL', 0, 0, -scull);
  nudgeBone(root, 'UpperArmR', 0, 0, scull);
  root.updateMatrixWorld(true);
  reconnectFeet(boneMap(root));
}
// Roof-fall ragdoll: the loose pose with a fast loose jiggle on every limb.
export function applyRagdoll(root: THREE.Object3D, t: number): void {
  applyPose(root, RAGDOLL, { feet: true });
  const j = (k: number) => Math.sin(t * 13 + k) * 0.4;
  nudgeBone(root, 'LowerArmL', j(0), 0, 0); nudgeBone(root, 'LowerArmR', j(2), 0, 0);
  nudgeBone(root, 'LowerLegL', j(4), 0, 0); nudgeBone(root, 'LowerLegR', j(6), 0, 0);
  root.updateMatrixWorld(true);
}
// Taxi hail: overlay the raised right arm (head stays on the clip), hand swinging side to side.
export function applyWave(root: THREE.Object3D, t: number): void {
  applyPose(root, NPC_WAVE, { only: ['UpperArmR', 'LowerArmR'] });
  nudgeBone(root, 'UpperArmR', 0, 0, Math.sin(t * 7) * 0.22);
  root.updateMatrixWorld(true);
}
// Cutscene talk: overlay both arms gesturing; gentle when talking, settled when not.
export function applyTalk(root: THREE.Object3D, t: number, talking: boolean): void {
  applyPose(root, NPC_TALK, { only: ['UpperArmL', 'LowerArmL', 'UpperArmR', 'LowerArmR'] });
  if (talking) {
    const g = Math.sin(t * 2.6) * 0.35;
    nudgeBone(root, 'UpperArmL', g, 0, 0);
    nudgeBone(root, 'UpperArmR', -g, 0, 0);
  }
  root.updateMatrixWorld(true);
}
